	
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-Container
          image:https://777777777773.dkr.ecr.us-east-2.amazonaws.com/myTestDocker:latest
          ports:
            - containerPort: 8443
      service:
        type: NodePort
        ports:
          - port: 443
            targetPort: 8443



	
  

	

